// ═══════════════════════════════════════════════════════════════
//  MONSTER MAKER — SRD 5.2 Spell Catalog (2024 Core Rules)
//  Compact reference: n=name, l=level (0=cantrip), s=school,
//  ct=casting time, r=range, c=components, d=duration,
//  k=concentration, x=terse effect summary
//  Source: SRD 5.2 (CC-BY-4.0, Wizards of the Coast)
// ═══════════════════════════════════════════════════════════════

var MM_SPELLS = [
// ── Cantrips (level 0) ──────────────────────────────────────────
{n:"Acid Splash",l:0,s:"Evocation",ct:"Action",r:"60 ft.",c:"V,S",d:"Instant",k:0,x:"Dex save or 1d6 acid in 5-ft sphere. +1d6 at lv 5/11/17."},
{n:"Blade Ward",l:0,s:"Abjuration",ct:"Action",r:"Self",c:"V,S",d:"1 round",k:0,x:"Attack rolls against you have disadvantage on next attacker's roll (2024: subtract 1d4 from one attack vs you)."},
{n:"Chill Touch",l:0,s:"Necromancy",ct:"Action",r:"Touch",c:"V,S",d:"Instant",k:0,x:"Melee spell attack, 1d10 necrotic, target can't regain HP until your next turn. +1d10 at lv 5/11/17."},
{n:"Dancing Lights",l:0,s:"Illusion",ct:"Action",r:"120 ft.",c:"V,S,M",d:"1 min",k:1,x:"Up to four floating lights you can move."},
{n:"Druidcraft",l:0,s:"Transmutation",ct:"Action",r:"30 ft.",c:"V,S",d:"Instant",k:0,x:"Minor nature effect: predict weather, bloom a flower, snuff a flame."},
{n:"Eldritch Blast",l:0,s:"Evocation",ct:"Action",r:"120 ft.",c:"V,S",d:"Instant",k:0,x:"Ranged spell attack, 1d10 force. Extra beam at lv 5/11/17."},
{n:"Elementalism",l:0,s:"Transmutation",ct:"Action",r:"30 ft.",c:"V,S",d:"Instant",k:0,x:"Minor elemental manipulation: gust, spark, shape water, smolder."},
{n:"Fire Bolt",l:0,s:"Evocation",ct:"Action",r:"120 ft.",c:"V,S",d:"Instant",k:0,x:"Ranged spell attack, 1d10 fire; ignites objects. +1d10 at lv 5/11/17."},
{n:"Friends",l:0,s:"Enchantment",ct:"Action",r:"10 ft.",c:"S,M",d:"1 min",k:1,x:"Advantage on Charisma checks vs one creature; it may notice after."},
{n:"Guidance",l:0,s:"Divination",ct:"Action",r:"Touch",c:"V,S",d:"1 min",k:1,x:"Target adds 1d4 to one ability check."},
{n:"Light",l:0,s:"Evocation",ct:"Action",r:"Touch",c:"V,M",d:"1 hour",k:0,x:"Object sheds bright light 20 ft, dim 20 ft."},
{n:"Mage Hand",l:0,s:"Conjuration",ct:"Action",r:"30 ft.",c:"V,S",d:"1 min",k:0,x:"Spectral hand manipulates objects up to 10 lb."},
{n:"Mending",l:0,s:"Transmutation",ct:"1 min",r:"Touch",c:"V,S,M",d:"Instant",k:0,x:"Repairs a single break or tear in an object."},
{n:"Message",l:0,s:"Transmutation",ct:"Action",r:"120 ft.",c:"S,M",d:"1 round",k:0,x:"Whisper a message to a creature; it can reply."},
{n:"Mind Sliver",l:0,s:"Enchantment",ct:"Action",r:"60 ft.",c:"V",d:"1 round",k:0,x:"Int save or 1d6 psychic and −1d4 on its next save. +1d6 at lv 5/11/17."},
{n:"Minor Illusion",l:0,s:"Illusion",ct:"Action",r:"30 ft.",c:"S,M",d:"1 min",k:0,x:"Sound or 5-ft-cube image; Investigation check vs spell DC reveals it."},
{n:"Poison Spray",l:0,s:"Necromancy",ct:"Action",r:"30 ft.",c:"V,S",d:"Instant",k:0,x:"Ranged spell attack, 1d12 poison (2024). +1d12 at lv 5/11/17."},
{n:"Prestidigitation",l:0,s:"Transmutation",ct:"Action",r:"10 ft.",c:"V,S",d:"1 hour",k:0,x:"Minor magical trick: spark, clean, flavor, mark."},
{n:"Produce Flame",l:0,s:"Conjuration",ct:"Bonus Action",r:"Self",c:"V,S",d:"10 min",k:0,x:"Flame in hand sheds light; throw for 1d8 fire (ranged attack). +1d8 at lv 5/11/17."},
{n:"Ray of Frost",l:0,s:"Evocation",ct:"Action",r:"60 ft.",c:"V,S",d:"Instant",k:0,x:"Ranged spell attack, 1d8 cold, −10 ft speed for a turn. +1d8 at lv 5/11/17."},
{n:"Resistance",l:0,s:"Abjuration",ct:"Action",r:"Touch",c:"V,S",d:"1 min",k:1,x:"Target adds 1d4 to one saving throw (2024: reduce damage taken by 1d4 once/turn)."},
{n:"Sacred Flame",l:0,s:"Evocation",ct:"Action",r:"60 ft.",c:"V,S",d:"Instant",k:0,x:"Dex save or 1d8 radiant; ignores cover. +1d8 at lv 5/11/17."},
{n:"Shillelagh",l:0,s:"Transmutation",ct:"Bonus Action",r:"Self",c:"V,S,M",d:"1 min",k:0,x:"Club/staff uses spellcasting mod, d8 damage (scales with level in 2024)."},
{n:"Shocking Grasp",l:0,s:"Evocation",ct:"Action",r:"Touch",c:"V,S",d:"Instant",k:0,x:"Melee spell attack, 1d8 lightning, no Opportunity Attacks from target. +1d8 at lv 5/11/17."},
{n:"Sorcerous Burst",l:0,s:"Evocation",ct:"Action",r:"120 ft.",c:"V,S",d:"Instant",k:0,x:"Ranged spell attack, 1d8 of chosen type; 8s explode up to spell mod times. +1d8 at lv 5/11/17."},
{n:"Spare the Dying",l:0,s:"Necromancy",ct:"Action",r:"15 ft.",c:"V,S",d:"Instant",k:0,x:"Stabilize a creature at 0 HP."},
{n:"Starry Wisp",l:0,s:"Evocation",ct:"Action",r:"60 ft.",c:"V,S",d:"Instant",k:0,x:"Ranged spell attack, 1d8 radiant; target emits dim light, can't be invisible. +1d8 at lv 5/11/17."},
{n:"Thaumaturgy",l:0,s:"Transmutation",ct:"Action",r:"30 ft.",c:"V",d:"Up to 1 min",k:0,x:"Minor wonder: booming voice, tremors, flickering flames."},
{n:"Thorn Whip",l:0,s:"Transmutation",ct:"Action",r:"30 ft.",c:"V,S,M",d:"Instant",k:0,x:"Melee spell attack, 1d6 piercing, pull Large or smaller 10 ft closer. +1d6 at lv 5/11/17."},
{n:"Thunderclap",l:0,s:"Evocation",ct:"Action",r:"Self (5-ft)",c:"S",d:"Instant",k:0,x:"Con save or 1d6 thunder to all within 5 ft. +1d6 at lv 5/11/17."},
{n:"True Strike",l:0,s:"Divination",ct:"Action",r:"Self",c:"S,M",d:"Instant",k:0,x:"Attack with a weapon using spellcasting mod; extra 1d6 radiant at lv 5/11/17 (2024)."},
{n:"Vicious Mockery",l:0,s:"Enchantment",ct:"Action",r:"60 ft.",c:"V",d:"Instant",k:0,x:"Wis save or 1d6 psychic and disadvantage on next attack. +1d6 at lv 5/11/17."},
{n:"Word of Radiance",l:0,s:"Evocation",ct:"Action",r:"Self (5-ft)",c:"V,M",d:"Instant",k:0,x:"Con save or 1d6 radiant to chosen creatures within 5 ft. +1d6 at lv 5/11/17."},

// ── Level 1 ────────────────────────────────────────────────────
{n:"Alarm",l:1,s:"Abjuration",ct:"1 min (R)",r:"30 ft.",c:"V,S,M",d:"8 hours",k:0,x:"Ward a 20-ft cube; mental or audible alert when crossed."},
{n:"Animal Friendship",l:1,s:"Enchantment",ct:"Action",r:"30 ft.",c:"V,S,M",d:"24 hours",k:0,x:"Beast Wis save or Charmed for the duration."},
{n:"Armor of Agathys",l:1,s:"Abjuration",ct:"Bonus Action",r:"Self",c:"V,S,M",d:"1 hour",k:0,x:"5 temp HP; melee attackers take 5 cold while they last. +5/+5 per slot level."},
{n:"Arms of Hadar",l:1,s:"Conjuration",ct:"Action",r:"Self (10-ft)",c:"V,S",d:"Instant",k:0,x:"Str save or 2d6 necrotic and no reactions this turn. +1d6 per slot."},
{n:"Bane",l:1,s:"Enchantment",ct:"Action",r:"30 ft.",c:"V,S,M",d:"1 min",k:1,x:"Up to 3 creatures, Cha save or −1d4 on attacks and saves."},
{n:"Bless",l:1,s:"Enchantment",ct:"Action",r:"30 ft.",c:"V,S,M",d:"1 min",k:1,x:"Up to 3 creatures add 1d4 to attacks and saves."},
{n:"Burning Hands",l:1,s:"Evocation",ct:"Action",r:"Self (15-ft cone)",c:"V,S",d:"Instant",k:0,x:"Dex save, 3d6 fire (half on success). +1d6 per slot."},
{n:"Charm Person",l:1,s:"Enchantment",ct:"Action",r:"30 ft.",c:"V,S",d:"1 hour",k:0,x:"Humanoid Wis save or Charmed; knows after. +1 target per slot."},
{n:"Chromatic Orb",l:1,s:"Evocation",ct:"Action",r:"90 ft.",c:"V,S,M",d:"Instant",k:0,x:"Ranged spell attack, 3d8 of chosen element; doubles leap to new targets (2024). +1d8 per slot."},
{n:"Color Spray",l:1,s:"Illusion",ct:"Action",r:"Self (15-ft cone)",c:"V,S,M",d:"1 round",k:0,x:"Con save or Blinded until end of your next turn (2024)."},
{n:"Command",l:1,s:"Enchantment",ct:"Action",r:"60 ft.",c:"V",d:"1 round",k:0,x:"Wis save or obey one-word command (Approach, Drop, Flee, Grovel, Halt). +1 target per slot."},
{n:"Compelled Duel",l:1,s:"Enchantment",ct:"Bonus Action",r:"30 ft.",c:"V",d:"1 min",k:1,x:"Wis save or disadvantage attacking others; speed 0 if moving away from you."},
{n:"Comprehend Languages",l:1,s:"Divination",ct:"Action (R)",r:"Self",c:"V,S,M",d:"1 hour",k:0,x:"Understand all spoken and written language."},
{n:"Create or Destroy Water",l:1,s:"Transmutation",ct:"Action",r:"30 ft.",c:"V,S,M",d:"Instant",k:0,x:"Make or remove up to 10 gallons of water. +10 gal per slot."},
{n:"Cure Wounds",l:1,s:"Abjuration",ct:"Action",r:"Touch",c:"V,S",d:"Instant",k:0,x:"Heal 2d8 + mod HP (2024). +2d8 per slot."},
{n:"Detect Evil and Good",l:1,s:"Divination",ct:"Action",r:"Self",c:"V,S",d:"10 min",k:1,x:"Sense aberrations, celestials, elementals, fey, fiends, undead within 30 ft."},
{n:"Detect Magic",l:1,s:"Divination",ct:"Action (R)",r:"Self",c:"V,S",d:"10 min",k:1,x:"Sense magic within 30 ft; action to see auras and school."},
{n:"Detect Poison and Disease",l:1,s:"Divination",ct:"Action (R)",r:"Self",c:"V,S,M",d:"10 min",k:1,x:"Sense poisons, poisonous creatures, diseases within 30 ft."},
{n:"Disguise Self",l:1,s:"Illusion",ct:"Action",r:"Self",c:"V,S",d:"1 hour",k:0,x:"Illusory change to your appearance; Investigation vs DC reveals."},
{n:"Dissonant Whispers",l:1,s:"Enchantment",ct:"Action",r:"60 ft.",c:"V",d:"Instant",k:0,x:"Wis save or 3d6 psychic and must move away using reaction. +1d6 per slot."},
{n:"Divine Favor",l:1,s:"Transmutation",ct:"Bonus Action",r:"Self",c:"V,S",d:"1 min",k:0,x:"Weapon attacks deal +1d4 radiant (2024: no concentration)."},
{n:"Divine Smite",l:1,s:"Evocation",ct:"Bonus Action",r:"Self",c:"V",d:"Instant",k:0,x:"On weapon hit: +2d8 radiant (+1d8 vs Undead/Fiends). +1d8 per slot."},
{n:"Ensnaring Strike",l:1,s:"Conjuration",ct:"Bonus Action",r:"Self",c:"V",d:"1 min",k:1,x:"Next weapon hit: Str save or Restrained by vines, 1d6 piercing/turn. +1d6 per slot."},
{n:"Entangle",l:1,s:"Conjuration",ct:"Action",r:"90 ft.",c:"V,S",d:"1 min",k:1,x:"20-ft square difficult terrain; Str save or Restrained."},
{n:"Expeditious Retreat",l:1,s:"Transmutation",ct:"Bonus Action",r:"Self",c:"V,S",d:"10 min",k:1,x:"Dash as a bonus action each turn."},
{n:"Faerie Fire",l:1,s:"Evocation",ct:"Action",r:"60 ft.",c:"V",d:"1 min",k:1,x:"20-ft cube; Dex save or outlined: attacks vs target have advantage, no invisibility."},
{n:"False Life",l:1,s:"Necromancy",ct:"Action",r:"Self",c:"V,S,M",d:"Instant",k:0,x:"Gain 2d4+4 temp HP (2024). +5 per slot."},
{n:"Feather Fall",l:1,s:"Transmutation",ct:"Reaction",r:"60 ft.",c:"V,M",d:"1 min",k:0,x:"Up to 5 falling creatures descend 60 ft/round, no fall damage."},
{n:"Find Familiar",l:1,s:"Conjuration",ct:"1 hour (R)",r:"10 ft.",c:"V,S,M",d:"Instant",k:0,x:"Summon a spirit familiar (bat, cat, owl, etc.); deliver touch spells, share senses."},
{n:"Fog Cloud",l:1,s:"Conjuration",ct:"Action",r:"120 ft.",c:"V,S",d:"1 hour",k:1,x:"20-ft-radius sphere heavily obscured. +20 ft radius per slot."},
{n:"Goodberry",l:1,s:"Conjuration",ct:"Action",r:"Self",c:"V,S,M",d:"24 hours",k:0,x:"Ten berries; eating one restores 1 HP and nourishes for a day."},
{n:"Grease",l:1,s:"Conjuration",ct:"Action",r:"60 ft.",c:"V,S,M",d:"1 min",k:0,x:"10-ft square difficult terrain; Dex save or Prone."},
{n:"Guiding Bolt",l:1,s:"Evocation",ct:"Action",r:"120 ft.",c:"V,S",d:"1 round",k:0,x:"Ranged spell attack, 4d6 radiant; next attack vs target has advantage. +1d6 per slot."},
{n:"Hail of Thorns",l:1,s:"Conjuration",ct:"Bonus Action",r:"Self",c:"V",d:"1 min",k:1,x:"Next ranged weapon hit: target and creatures within 5 ft, Dex save or 1d10 piercing. +1d10 per slot."},
{n:"Healing Word",l:1,s:"Abjuration",ct:"Bonus Action",r:"60 ft.",c:"V",d:"Instant",k:0,x:"Heal 2d4 + mod HP at range (2024). +2d4 per slot."},
{n:"Hellish Rebuke",l:1,s:"Evocation",ct:"Reaction",r:"60 ft.",c:"V,S",d:"Instant",k:0,x:"When damaged: attacker Dex save, 2d10 fire (half on success). +1d10 per slot."},
{n:"Heroism",l:1,s:"Enchantment",ct:"Action",r:"Touch",c:"V,S",d:"1 min",k:1,x:"Immune to Frightened; gain spellcasting-mod temp HP each turn. +1 target per slot."},
{n:"Hex",l:1,s:"Enchantment",ct:"Bonus Action",r:"90 ft.",c:"V,S,M",d:"1 hour",k:1,x:"Curse a creature: +1d6 necrotic on your hits, disadvantage on chosen ability checks."},
{n:"Hunter's Mark",l:1,s:"Divination",ct:"Bonus Action",r:"90 ft.",c:"V",d:"1 hour",k:1,x:"Mark a creature: +1d6 force on weapon hits; track it easily."},
{n:"Ice Knife",l:1,s:"Conjuration",ct:"Action",r:"60 ft.",c:"S,M",d:"Instant",k:0,x:"Ranged spell attack, 1d10 piercing; burst: Dex save or 2d6 cold within 5 ft. +1d6 cold per slot."},
{n:"Identify",l:1,s:"Divination",ct:"1 min (R)",r:"Touch",c:"V,S,M",d:"Instant",k:0,x:"Learn an item's magical properties and how to use them."},
{n:"Illusory Script",l:1,s:"Illusion",ct:"1 min (R)",r:"Touch",c:"S,M",d:"10 days",k:0,x:"Hidden writing only designated readers can perceive."},
{n:"Inflict Wounds",l:1,s:"Necromancy",ct:"Action",r:"Touch",c:"V,S",d:"Instant",k:0,x:"Con save, 2d10 necrotic, half on success (2024). +1d10 per slot."},
{n:"Jump",l:1,s:"Transmutation",ct:"Bonus Action",r:"Touch",c:"V,S,M",d:"1 min",k:0,x:"Target's jump distance is 30 ft when it moves (2024)."},
{n:"Longstrider",l:1,s:"Transmutation",ct:"Action",r:"Touch",c:"V,S,M",d:"1 hour",k:0,x:"+10 ft speed. +1 target per slot."},
{n:"Mage Armor",l:1,s:"Abjuration",ct:"Action",r:"Touch",c:"V,S,M",d:"8 hours",k:0,x:"Unarmored target's base AC becomes 13 + Dex mod."},
{n:"Magic Missile",l:1,s:"Evocation",ct:"Action",r:"120 ft.",c:"V,S",d:"Instant",k:0,x:"Three darts auto-hit for 1d4+1 force each. +1 dart per slot."},
{n:"Protection from Evil and Good",l:1,s:"Abjuration",ct:"Action",r:"Touch",c:"V,S,M",d:"10 min",k:1,x:"Listed types have disadvantage attacking target; no charm/fright/possession."},
{n:"Purify Food and Drink",l:1,s:"Transmutation",ct:"Action (R)",r:"10 ft.",c:"V,S",d:"Instant",k:0,x:"Removes poison and rot from food and drink in 5-ft sphere."},
{n:"Ray of Sickness",l:1,s:"Necromancy",ct:"Action",r:"60 ft.",c:"V,S",d:"Instant",k:0,x:"Ranged spell attack, 2d8 poison and Con save or Poisoned 1 turn. +1d8 per slot."},
{n:"Sanctuary",l:1,s:"Abjuration",ct:"Bonus Action",r:"30 ft.",c:"V,S,M",d:"1 min",k:0,x:"Attackers must make Wis save or choose a new target."},
{n:"Searing Smite",l:1,s:"Evocation",ct:"Bonus Action",r:"Self",c:"V",d:"1 min",k:0,x:"On weapon hit: +1d6 fire, target burns 1d6/turn until Con save (2024: no conc.). +1d6 per slot."},
{n:"Shield",l:1,s:"Abjuration",ct:"Reaction",r:"Self",c:"V,S",d:"1 round",k:0,x:"+5 AC until next turn, including vs triggering attack; blocks Magic Missile."},
{n:"Shield of Faith",l:1,s:"Abjuration",ct:"Bonus Action",r:"60 ft.",c:"V,S,M",d:"10 min",k:1,x:"+2 AC to one creature."},
{n:"Silent Image",l:1,s:"Illusion",ct:"Action",r:"60 ft.",c:"V,S,M",d:"10 min",k:1,x:"15-ft-cube visual illusion you can move."},
{n:"Sleep",l:1,s:"Enchantment",ct:"Action",r:"60 ft.",c:"V,S,M",d:"1 min",k:1,x:"5-ft sphere: Wis save or Incapacitated then Unconscious (2024 version)."},
{n:"Speak with Animals",l:1,s:"Divination",ct:"Action (R)",r:"Self",c:"V,S",d:"10 min",k:0,x:"Comprehend and verbally communicate with Beasts."},
{n:"Tasha's Hideous Laughter",l:1,s:"Enchantment",ct:"Action",r:"30 ft.",c:"V,S,M",d:"1 min",k:1,x:"Wis save or fall Prone laughing, Incapacitated; resave when damaged."},
{n:"Tenser's Floating Disk",l:1,s:"Conjuration",ct:"Action (R)",r:"30 ft.",c:"V,S,M",d:"1 hour",k:0,x:"Floating 3-ft disk carries 500 lb, follows you."},
{n:"Thunderous Smite",l:1,s:"Evocation",ct:"Bonus Action",r:"Self",c:"V",d:"Instant",k:0,x:"On weapon hit: +2d6 thunder, Str save or pushed 10 ft and Prone. +1d6 per slot."},
{n:"Thunderwave",l:1,s:"Evocation",ct:"Action",r:"Self (15-ft cube)",c:"V,S",d:"Instant",k:0,x:"Con save, 2d8 thunder and pushed 10 ft (half, no push on success). +1d8 per slot."},
{n:"Unseen Servant",l:1,s:"Conjuration",ct:"Action (R)",r:"60 ft.",c:"V,S,M",d:"1 hour",k:0,x:"Invisible force performs simple tasks."},
{n:"Witch Bolt",l:1,s:"Evocation",ct:"Action",r:"60 ft.",c:"V,S,M",d:"1 min",k:1,x:"Ranged spell attack, 2d12 lightning; repeat 1d12 as bonus action (2024). +1d12 per slot."},
{n:"Wrathful Smite",l:1,s:"Necromancy",ct:"Bonus Action",r:"Self",c:"V",d:"1 min",k:0,x:"On weapon hit: +1d6 necrotic, Wis save or Frightened until save (2024: no conc.). +1d6 per slot."},

// ── Level 2 ────────────────────────────────────────────────────
{n:"Aid",l:2,s:"Abjuration",ct:"Action",r:"30 ft.",c:"V,S,M",d:"8 hours",k:0,x:"Three creatures gain +5 current and max HP. +5 per slot."},
{n:"Alter Self",l:2,s:"Transmutation",ct:"Action",r:"Self",c:"V,S",d:"1 hour",k:1,x:"Aquatic adaptation, appearance change, or natural weapons (1d6+mod)."},
{n:"Animal Messenger",l:2,s:"Enchantment",ct:"Action (R)",r:"30 ft.",c:"V,S,M",d:"24 hours",k:0,x:"Tiny beast carries a 25-word message to a described recipient."},
{n:"Arcane Lock",l:2,s:"Abjuration",ct:"Action",r:"Touch",c:"V,S,M",d:"Until dispelled",k:0,x:"Lock an object; +10 to DC to break or pick."},
{n:"Arcane Vigor",l:2,s:"Abjuration",ct:"Bonus Action",r:"Self",c:"V",d:"Instant",k:0,x:"Spend 1-2 Hit Dice, regain HP (2024). +1 die per slot."},
{n:"Augury",l:2,s:"Divination",ct:"1 min (R)",r:"Self",c:"V,S,M",d:"Instant",k:0,x:"Omen about a course of action: Weal, Woe, both, or neither."},
{n:"Barkskin",l:2,s:"Transmutation",ct:"Bonus Action",r:"Touch",c:"V,S,M",d:"1 hour",k:0,x:"Target gains 2d4 temp HP at start of each turn (2024 version)."},
{n:"Beast Sense",l:2,s:"Divination",ct:"Action (R)",r:"Touch",c:"S",d:"1 hour",k:1,x:"See and hear through a willing beast's senses."},
{n:"Blindness/Deafness",l:2,s:"Transmutation",ct:"Action",r:"120 ft.",c:"V",d:"1 min",k:0,x:"Con save or Blinded or Deafened; resave each turn. +1 target per slot."},
{n:"Blur",l:2,s:"Illusion",ct:"Action",r:"Self",c:"V",d:"1 min",k:1,x:"Attack rolls against you have disadvantage."},
{n:"Branding Smite",l:2,s:"Evocation",ct:"Bonus Action",r:"Self",c:"V",d:"1 min",k:0,x:"On weapon hit: +2d6 radiant, target glows, can't be invisible. +1d6 per slot."},
{n:"Calm Emotions",l:2,s:"Enchantment",ct:"Action",r:"60 ft.",c:"V,S",d:"1 min",k:1,x:"20-ft sphere: suppress charm/fear or hostility (Cha save)."},
{n:"Cloud of Daggers",l:2,s:"Conjuration",ct:"Action",r:"60 ft.",c:"V,S,M",d:"1 min",k:1,x:"5-ft cube deals 4d4 slashing on enter/start. +2d4 per slot."},
{n:"Continual Flame",l:2,s:"Evocation",ct:"Action",r:"Touch",c:"V,S,M",d:"Until dispelled",k:0,x:"Permanent heatless torch flame on an object."},
{n:"Cordon of Arrows",l:2,s:"Transmutation",ct:"Action",r:"Touch",c:"V,S,M",d:"8 hours",k:0,x:"Plant 4 ammo; they fire at creatures within 30 ft, Dex save or 1d6 piercing. +2 ammo per slot."},
{n:"Crown of Madness",l:2,s:"Enchantment",ct:"Action",r:"120 ft.",c:"V,S",d:"1 min",k:1,x:"Humanoid Wis save or Charmed, must attack creatures you choose."},
{n:"Darkness",l:2,s:"Evocation",ct:"Action",r:"60 ft.",c:"V,M",d:"10 min",k:1,x:"15-ft-radius magical darkness; darkvision can't see through."},
{n:"Darkvision",l:2,s:"Transmutation",ct:"Action",r:"Touch",c:"V,S,M",d:"8 hours",k:0,x:"Target gains Darkvision 60 ft."},
{n:"Detect Thoughts",l:2,s:"Divination",ct:"Action",r:"Self",c:"V,S,M",d:"1 min",k:1,x:"Read surface thoughts within 30 ft; probe deeper with Wis save."},
{n:"Dragon's Breath",l:2,s:"Transmutation",ct:"Bonus Action",r:"Touch",c:"V,S,M",d:"1 min",k:1,x:"Target can exhale 15-ft cone, Dex save or 3d6 chosen element. +1d6 per slot."},
{n:"Enhance Ability",l:2,s:"Transmutation",ct:"Action",r:"Touch",c:"V,S,M",d:"1 hour",k:1,x:"Advantage on checks with one ability. +1 target per slot."},
{n:"Enlarge/Reduce",l:2,s:"Transmutation",ct:"Action",r:"30 ft.",c:"V,S,M",d:"1 min",k:1,x:"Grow (advantage Str, +1d4 weapon dmg) or shrink (−1d4, disadvantage Str)."},
{n:"Enthrall",l:2,s:"Enchantment",ct:"Action",r:"60 ft.",c:"V,S",d:"1 min",k:0,x:"Wis save or disadvantage on Perception to notice others (2024: Deafened to others)."},
{n:"Find Steed",l:2,s:"Conjuration",ct:"Action",r:"30 ft.",c:"V,S",d:"Instant",k:0,x:"Summon an otherworldly mount with shared bond."},
{n:"Find Traps",l:2,s:"Divination",ct:"Action",r:"120 ft.",c:"V,S",d:"Instant",k:0,x:"Sense presence (not location) of traps in line of sight."},
{n:"Flame Blade",l:2,s:"Evocation",ct:"Bonus Action",r:"Self",c:"V,S,M",d:"10 min",k:1,x:"Fiery scimitar: melee spell attack, 3d6 fire. +1d6 per 2 slots."},
{n:"Flaming Sphere",l:2,s:"Conjuration",ct:"Action",r:"60 ft.",c:"V,S,M",d:"1 min",k:1,x:"5-ft sphere; Dex save or 2d6 fire adjacent; ram as bonus action. +1d6 per slot."},
{n:"Gentle Repose",l:2,s:"Necromancy",ct:"Action (R)",r:"Touch",c:"V,S,M",d:"10 days",k:0,x:"Corpse protected from decay and undeath."},
{n:"Gust of Wind",l:2,s:"Evocation",ct:"Action",r:"Self (60-ft line)",c:"V,S,M",d:"1 min",k:1,x:"Str save or pushed 15 ft; halved movement toward you."},
{n:"Heat Metal",l:2,s:"Transmutation",ct:"Action",r:"60 ft.",c:"V,S,M",d:"1 min",k:1,x:"Metal object glows: 2d8 fire to holder, Con save or drop it. +1d8 per slot."},
{n:"Hold Person",l:2,s:"Enchantment",ct:"Action",r:"60 ft.",c:"V,S,M",d:"1 min",k:1,x:"Humanoid Wis save or Paralyzed; resave each turn. +1 target per slot."},
{n:"Invisibility",l:2,s:"Illusion",ct:"Action",r:"Touch",c:"V,S,M",d:"1 hour",k:1,x:"Target Invisible until it attacks or casts. +1 target per slot."},
{n:"Knock",l:2,s:"Transmutation",ct:"Action",r:"60 ft.",c:"V",d:"Instant",k:0,x:"Open a locked door/container; loud knock audible 300 ft."},
{n:"Lesser Restoration",l:2,s:"Abjuration",ct:"Bonus Action",r:"Touch",c:"V,S",d:"Instant",k:0,x:"End one condition: Blinded, Deafened, Paralyzed, or Poisoned (2024: bonus action)."},
{n:"Levitate",l:2,s:"Transmutation",ct:"Action",r:"60 ft.",c:"V,S,M",d:"10 min",k:1,x:"Target rises up to 20 ft (Con save if unwilling)."},
{n:"Locate Animals or Plants",l:2,s:"Divination",ct:"Action (R)",r:"Self",c:"V,S,M",d:"Instant",k:0,x:"Sense direction of nearest named beast or plant within 5 miles."},
{n:"Locate Object",l:2,s:"Divination",ct:"Action",r:"Self",c:"V,S,M",d:"10 min",k:1,x:"Sense direction to a familiar object within 1,000 ft."},
{n:"Magic Mouth",l:2,s:"Illusion",ct:"1 min (R)",r:"30 ft.",c:"V,S,M",d:"Until dispelled",k:0,x:"Object speaks a 25-word message when triggered."},
{n:"Magic Weapon",l:2,s:"Transmutation",ct:"Bonus Action",r:"Touch",c:"V,S",d:"1 hour",k:0,x:"Weapon becomes +1 magic weapon (2024: no conc.). +2/+3 at slot 3/5+."},
{n:"Melf's Acid Arrow",l:2,s:"Evocation",ct:"Action",r:"90 ft.",c:"V,S,M",d:"Instant",k:0,x:"Ranged spell attack, 4d4 acid + 2d4 next turn. +1d4/+1d4 per slot."},
{n:"Mind Spike",l:2,s:"Divination",ct:"Action",r:"120 ft.",c:"S",d:"1 hour",k:1,x:"Wis save, 3d8 psychic (half on success); you know target's location. +1d8 per slot."},
{n:"Mirror Image",l:2,s:"Illusion",ct:"Action",r:"Self",c:"V,S",d:"1 min",k:0,x:"Three duplicates misdirect attacks (AC 10+Dex each)."},
{n:"Misty Step",l:2,s:"Conjuration",ct:"Bonus Action",r:"Self",c:"V",d:"Instant",k:0,x:"Teleport up to 30 ft to a visible spot."},
{n:"Moonbeam",l:2,s:"Evocation",ct:"Action",r:"120 ft.",c:"V,S,M",d:"1 min",k:1,x:"5-ft-radius beam: Con save, 2d10 radiant on enter/start. +1d10 per slot."},
{n:"Pass Without Trace",l:2,s:"Abjuration",ct:"Action",r:"Self",c:"V,S,M",d:"1 hour",k:1,x:"+10 Stealth to group within 30 ft; no tracks."},
{n:"Phantasmal Force",l:2,s:"Illusion",ct:"Action",r:"60 ft.",c:"V,S,M",d:"1 min",k:1,x:"Int save or perceive a 10-ft-cube illusion as real; 1d6 psychic/turn."},
{n:"Prayer of Healing",l:2,s:"Abjuration",ct:"10 min",r:"30 ft.",c:"V",d:"Instant",k:0,x:"Up to 5 creatures heal 2d8+mod and gain Short Rest benefit (2024). +1d8 per slot."},
{n:"Protection from Poison",l:2,s:"Abjuration",ct:"Action",r:"Touch",c:"V,S",d:"1 hour",k:0,x:"End one poison; advantage vs Poisoned; resistance to poison damage."},
{n:"Ray of Enfeeblement",l:2,s:"Necromancy",ct:"Action",r:"60 ft.",c:"V,S",d:"1 min",k:1,x:"Ranged spell attack; target's Str-based damage halved (2024: Con save, damage on hit)."},
{n:"Rope Trick",l:2,s:"Transmutation",ct:"Action",r:"Touch",c:"V,S,M",d:"1 hour",k:0,x:"Rope leads to extradimensional space holding 8 creatures."},
{n:"Scorching Ray",l:2,s:"Evocation",ct:"Action",r:"120 ft.",c:"V,S",d:"Instant",k:0,x:"Three rays, ranged spell attacks, 2d6 fire each. +1 ray per slot."},
{n:"See Invisibility",l:2,s:"Divination",ct:"Action",r:"Self",c:"V,S,M",d:"1 hour",k:0,x:"See Invisible creatures and into the Ethereal Plane."},
{n:"Shatter",l:2,s:"Evocation",ct:"Action",r:"60 ft.",c:"V,S,M",d:"Instant",k:0,x:"10-ft sphere: Con save, 3d8 thunder (half on success). +1d8 per slot."},
{n:"Shining Smite",l:2,s:"Transmutation",ct:"Bonus Action",r:"Self",c:"V",d:"1 min",k:1,x:"On weapon hit: +2d6 radiant; target sheds light, no invisibility (2024, was Branding Smite)."},
{n:"Silence",l:2,s:"Illusion",ct:"Action (R)",r:"120 ft.",c:"V,S",d:"10 min",k:1,x:"20-ft sphere of no sound; blocks V-component casting."},
{n:"Spider Climb",l:2,s:"Transmutation",ct:"Action",r:"Touch",c:"V,S,M",d:"1 hour",k:1,x:"Climb walls and ceilings, hands free; climb speed = speed."},
{n:"Spike Growth",l:2,s:"Transmutation",ct:"Action",r:"150 ft.",c:"V,S,M",d:"10 min",k:1,x:"20-ft radius camouflaged spikes: 2d4 per 5 ft moved; difficult terrain."},
{n:"Spiritual Weapon",l:2,s:"Evocation",ct:"Bonus Action",r:"60 ft.",c:"V,S",d:"1 min",k:1,x:"Floating weapon: melee spell attack, 1d8+mod force; move and strike as bonus action (2024: conc.). +1d8 per 2 slots."},
{n:"Suggestion",l:2,s:"Enchantment",ct:"Action",r:"30 ft.",c:"V,M",d:"8 hours",k:1,x:"Wis save or follow a reasonable-sounding course of action."},
{n:"Warding Bond",l:2,s:"Abjuration",ct:"Action",r:"Touch",c:"V,S,M",d:"1 hour",k:0,x:"Target gets +1 AC/saves and resistance to all; you share its damage."},
{n:"Web",l:2,s:"Conjuration",ct:"Action",r:"60 ft.",c:"V,S,M",d:"1 hour",k:1,x:"20-ft cube of webs; Dex save or Restrained; flammable."},
{n:"Zone of Truth",l:2,s:"Enchantment",ct:"Action",r:"60 ft.",c:"V,S",d:"10 min",k:0,x:"15-ft sphere: Cha save or unable to speak deliberate lies."},

// ── Level 3 ────────────────────────────────────────────────────
{n:"Animate Dead",l:3,s:"Necromancy",ct:"1 min",r:"10 ft.",c:"V,S,M",d:"Instant",k:0,x:"Raise a skeleton or zombie servant from remains; control 24h. +2 undead per slot."},
{n:"Aura of Vitality",l:3,s:"Abjuration",ct:"Action",r:"Self (30-ft)",c:"V",d:"1 min",k:1,x:"Bonus action each turn: heal a creature in aura 2d6."},
{n:"Beacon of Hope",l:3,s:"Abjuration",ct:"Action",r:"30 ft.",c:"V,S",d:"1 min",k:1,x:"Targets get advantage on Wis/death saves and max healing."},
{n:"Bestow Curse",l:3,s:"Necromancy",ct:"Action",r:"Touch",c:"V,S",d:"1 min",k:1,x:"Wis save or cursed: disadvantage with an ability, vs you, Wis save to act, or +1d8 necrotic from you."},
{n:"Blinding Smite",l:3,s:"Evocation",ct:"Bonus Action",r:"Self",c:"V",d:"1 min",k:0,x:"On weapon hit: +3d8 radiant, Con save or Blinded until save. +1d8 per slot."},
{n:"Blink",l:3,s:"Transmutation",ct:"Action",r:"Self",c:"V,S",d:"1 min",k:0,x:"Each turn 11+ on d20: vanish to Ethereal, return 10 ft away."},
{n:"Call Lightning",l:3,s:"Conjuration",ct:"Action",r:"120 ft.",c:"V,S",d:"10 min",k:1,x:"Bolt each turn: Dex save, 3d10 lightning in 5-ft radius. +1d10 per slot."},
{n:"Clairvoyance",l:3,s:"Divination",ct:"10 min",r:"1 mile",c:"V,S,M",d:"10 min",k:1,x:"Invisible sensor at a familiar location; see or hear through it."},
{n:"Conjure Animals",l:3,s:"Conjuration",ct:"Action",r:"60 ft.",c:"V,S",d:"10 min",k:1,x:"Spirit pack: 30-ft Emanation, Dex save or 3d10 slashing (2024 version). +1d10 per slot."},
{n:"Conjure Barrage",l:3,s:"Conjuration",ct:"Action",r:"Self (60-ft cone)",c:"V,S,M",d:"Instant",k:0,x:"Dex save, 5d8 weapon-type damage in cone (2024: force). +1d8 per slot."},
{n:"Counterspell",l:3,s:"Abjuration",ct:"Reaction",r:"60 ft.",c:"S",d:"Instant",k:0,x:"Interrupt a spell: caster Con save or spell fails (2024 version)."},
{n:"Create Food and Water",l:3,s:"Conjuration",ct:"Action",r:"30 ft.",c:"V,S",d:"Instant",k:0,x:"Feed 15 humanoids: 45 lb food, 30 gal water."},
{n:"Crusader's Mantle",l:3,s:"Evocation",ct:"Action",r:"Self (30-ft)",c:"V",d:"1 min",k:1,x:"Allies in aura deal +1d4 radiant on weapon hits."},
{n:"Daylight",l:3,s:"Evocation",ct:"Action",r:"60 ft.",c:"V,S",d:"1 hour",k:0,x:"60-ft-radius bright light; dispels lower-level magical darkness."},
{n:"Dispel Magic",l:3,s:"Abjuration",ct:"Action",r:"120 ft.",c:"V,S",d:"Instant",k:0,x:"End spells of level ≤3 on a target; higher needs ability check DC 10+level."},
{n:"Elemental Weapon",l:3,s:"Transmutation",ct:"Action",r:"Touch",c:"V,S",d:"1 hour",k:1,x:"Weapon +1 and +1d4 chosen element. +2/2d4 at slot 5, +3/3d4 at slot 7."},
{n:"Fear",l:3,s:"Illusion",ct:"Action",r:"Self (30-ft cone)",c:"V,S,M",d:"1 min",k:1,x:"Wis save or drop held item and become Frightened, must flee."},
{n:"Feign Death",l:3,s:"Necromancy",ct:"Action (R)",r:"Touch",c:"V,S,M",d:"1 hour",k:0,x:"Willing target appears dead; resistance to all but psychic."},
{n:"Fireball",l:3,s:"Evocation",ct:"Action",r:"150 ft.",c:"V,S,M",d:"Instant",k:0,x:"20-ft-radius sphere: Dex save, 8d6 fire (half on success). +1d6 per slot."},
{n:"Fly",l:3,s:"Transmutation",ct:"Action",r:"Touch",c:"V,S,M",d:"10 min",k:1,x:"Target gains 60 ft fly speed. +1 target per slot."},
{n:"Gaseous Form",l:3,s:"Transmutation",ct:"Action",r:"Touch",c:"V,S,M",d:"1 hour",k:1,x:"Target becomes a misty cloud: fly 10 ft, resistance to nonmagical damage."},
{n:"Glyph of Warding",l:3,s:"Abjuration",ct:"1 hour",r:"Touch",c:"V,S,M",d:"Until dispelled",k:0,x:"Hidden glyph: explosive (5d8 element) or stored spell triggers."},
{n:"Haste",l:3,s:"Transmutation",ct:"Action",r:"30 ft.",c:"V,S,M",d:"1 min",k:1,x:"Double speed, +2 AC, advantage Dex saves, extra limited action; lethargy after."},
{n:"Hunger of Hadar",l:3,s:"Conjuration",ct:"Action",r:"150 ft.",c:"V,S,M",d:"1 min",k:1,x:"20-ft void sphere: 2d6 cold at start, Dex save or 2d6 acid at end; blinds inside."},
{n:"Hypnotic Pattern",l:3,s:"Illusion",ct:"Action",r:"120 ft.",c:"S,M",d:"1 min",k:1,x:"30-ft cube: Wis save or Charmed and Incapacitated, speed 0."},
{n:"Leomund's Tiny Hut",l:3,s:"Evocation",ct:"1 min (R)",r:"Self (10-ft)",c:"V,S,M",d:"8 hours",k:0,x:"Immobile dome shelters 9 creatures; objects can't pass."},
{n:"Lightning Arrow",l:3,s:"Transmutation",ct:"Bonus Action",r:"Self",c:"V,S",d:"1 min",k:1,x:"Next ranged weapon attack: 4d8 lightning, 10-ft burst Dex save or 2d8. +1d8 per slot."},
{n:"Lightning Bolt",l:3,s:"Evocation",ct:"Action",r:"Self (100-ft line)",c:"V,S,M",d:"Instant",k:0,x:"Dex save, 8d6 lightning in a 100×5-ft line (half on success). +1d6 per slot."},
{n:"Magic Circle",l:3,s:"Abjuration",ct:"1 min",r:"10 ft.",c:"V,S,M",d:"1 hour",k:0,x:"10-ft cylinder bars chosen types (Celestial/Elemental/Fey/Fiend/Undead)."},
{n:"Major Image",l:3,s:"Illusion",ct:"Action",r:"120 ft.",c:"V,S,M",d:"10 min",k:1,x:"20-ft-cube illusion with sound, smell, temperature."},
{n:"Mass Healing Word",l:3,s:"Abjuration",ct:"Bonus Action",r:"60 ft.",c:"V",d:"Instant",k:0,x:"Up to 6 creatures heal 2d4+mod (2024). +1d4 per slot."},
{n:"Meld into Stone",l:3,s:"Transmutation",ct:"Action (R)",r:"Touch",c:"V,S",d:"8 hours",k:0,x:"Step inside a stone object or surface; muffled awareness."},
{n:"Nondetection",l:3,s:"Abjuration",ct:"Action",r:"Touch",c:"V,S,M",d:"8 hours",k:0,x:"Target hidden from divination magic and scrying."},
{n:"Phantom Steed",l:3,s:"Illusion",ct:"1 min (R)",r:"30 ft.",c:"V,S",d:"1 hour",k:0,x:"Quasi-real horse, speed 100 ft, ride only."},
{n:"Plant Growth",l:3,s:"Transmutation",ct:"Action or 8 hours",r:"150 ft.",c:"V,S",d:"Instant",k:0,x:"Overgrow 100-ft radius (4x movement cost) or enrich land for a year."},
{n:"Protection from Energy",l:3,s:"Abjuration",ct:"Action",r:"Touch",c:"V,S",d:"1 hour",k:1,x:"Resistance to acid, cold, fire, lightning, or thunder."},
{n:"Remove Curse",l:3,s:"Abjuration",ct:"Action",r:"Touch",c:"V,S",d:"Instant",k:0,x:"End all curses on a creature or break cursed-item attunement."},
{n:"Revivify",l:3,s:"Necromancy",ct:"Action",r:"Touch",c:"V,S,M",d:"Instant",k:0,x:"Return a creature dead ≤1 min to life with 1 HP."},
{n:"Sending",l:3,s:"Divination",ct:"Action",r:"Unlimited",c:"V,S,M",d:"1 round",k:0,x:"25-word message to a familiar creature anywhere; it can reply."},
{n:"Sleet Storm",l:3,s:"Conjuration",ct:"Action",r:"150 ft.",c:"V,S,M",d:"1 min",k:1,x:"40-ft cylinder: heavily obscured, difficult terrain, Dex save or Prone; breaks concentration."},
{n:"Slow",l:3,s:"Transmutation",ct:"Action",r:"120 ft.",c:"V,S,M",d:"1 min",k:1,x:"Up to 6 in 40-ft cube: Wis save or half speed, −2 AC/Dex saves, 1 attack, no reactions."},
{n:"Speak with Dead",l:3,s:"Necromancy",ct:"Action",r:"10 ft.",c:"V,S,M",d:"10 min",k:0,x:"Corpse answers 5 questions; knows only what it knew in life."},
{n:"Speak with Plants",l:3,s:"Transmutation",ct:"Action",r:"Self (30-ft)",c:"V,S",d:"10 min",k:0,x:"Question plants; ease or hinder terrain they cover."},
{n:"Spirit Guardians",l:3,s:"Conjuration",ct:"Action",r:"Self (15-ft)",c:"V,S,M",d:"10 min",k:1,x:"Aura: enemies half speed, Wis save or 3d8 radiant/necrotic. +1d8 per slot."},
{n:"Stinking Cloud",l:3,s:"Conjuration",ct:"Action",r:"90 ft.",c:"V,S,M",d:"1 min",k:1,x:"20-ft sphere: Con save or lose action retching."},
{n:"Summon Fey",l:3,s:"Conjuration",ct:"Action",r:"90 ft.",c:"V,S,M",d:"1 hour",k:1,x:"Fey spirit (Fuming/Mirthful/Tricksy) fights alongside you."},
{n:"Summon Undead",l:3,s:"Necromancy",ct:"Action",r:"90 ft.",c:"V,S,M",d:"1 hour",k:1,x:"Undead spirit (Ghostly/Putrid/Skeletal) fights alongside you."},
{n:"Tongues",l:3,s:"Divination",ct:"Action",r:"Touch",c:"V,M",d:"1 hour",k:0,x:"Understand and be understood in any spoken language."},
{n:"Vampiric Touch",l:3,s:"Necromancy",ct:"Action",r:"Self",c:"V,S",d:"1 min",k:1,x:"Melee spell attack, 3d6 necrotic; heal half dealt. +1d6 per slot."},
{n:"Water Breathing",l:3,s:"Transmutation",ct:"Action (R)",r:"30 ft.",c:"V,S,M",d:"24 hours",k:0,x:"Ten creatures can breathe underwater."},
{n:"Water Walk",l:3,s:"Transmutation",ct:"Action (R)",r:"30 ft.",c:"V,S,M",d:"1 hour",k:0,x:"Ten creatures walk on liquid surfaces."},
{n:"Wind Wall",l:3,s:"Evocation",ct:"Action",r:"120 ft.",c:"V,S,M",d:"1 min",k:1,x:"50×15-ft wall of wind: Str save or 4d8 bludgeoning (2024: 4d8); deflects missiles, gas."},

// ── Level 4 ────────────────────────────────────────────────────
{n:"Arcane Eye",l:4,s:"Divination",ct:"Action",r:"30 ft.",c:"V,S,M",d:"1 hour",k:1,x:"Invisible flying eye with darkvision; move 30 ft/turn."},
{n:"Aura of Life",l:4,s:"Abjuration",ct:"Action",r:"Self (30-ft)",c:"V",d:"10 min",k:1,x:"Aura: resistance to necrotic, max HP can't drop, 0-HP allies regain 1 HP at start."},
{n:"Aura of Purity",l:4,s:"Abjuration",ct:"Action",r:"Self (30-ft)",c:"V",d:"10 min",k:1,x:"Aura: can't be Diseased, resistance to poison, advantage vs conditions."},
{n:"Banishment",l:4,s:"Abjuration",ct:"Action",r:"60 ft.",c:"V,S,M",d:"1 min",k:1,x:"Cha save or banished to another plane; permanent if native elsewhere and full minute. +1 target per slot."},
{n:"Blight",l:4,s:"Necromancy",ct:"Action",r:"30 ft.",c:"V,S",d:"Instant",k:0,x:"Con save, 8d8 necrotic (half on success); plants have disadvantage. +1d8 per slot."},
{n:"Charm Monster",l:4,s:"Enchantment",ct:"Action",r:"30 ft.",c:"V,S",d:"1 hour",k:0,x:"Wis save or Charmed; knows after. +1 target per slot."},
{n:"Compulsion",l:4,s:"Enchantment",ct:"Action",r:"30 ft.",c:"V,S",d:"1 min",k:1,x:"Wis save or you steer its movement each turn."},
{n:"Confusion",l:4,s:"Enchantment",ct:"Action",r:"90 ft.",c:"V,S,M",d:"1 min",k:1,x:"10-ft sphere: Wis save or act randomly each turn. +5 ft radius per slot."},
{n:"Conjure Minor Elementals",l:4,s:"Conjuration",ct:"Action",r:"Self (15-ft)",c:"V,S",d:"10 min",k:1,x:"Emanation adds 2d8 element damage to your attacks; difficult terrain (2024). x2 dice per slot."},
{n:"Conjure Woodland Beings",l:4,s:"Conjuration",ct:"Action",r:"Self (10-ft)",c:"V,S",d:"10 min",k:1,x:"Fey ring: Wis save or 5d8 force and 0 speed (2024). +1d8 per slot."},
{n:"Control Water",l:4,s:"Transmutation",ct:"Action",r:"300 ft.",c:"V,S,M",d:"10 min",k:1,x:"Flood, part, redirect, or whirlpool a 100-ft cube of water."},
{n:"Death Ward",l:4,s:"Abjuration",ct:"Action",r:"Touch",c:"V,S",d:"8 hours",k:0,x:"First time target would drop to 0 HP, it drops to 1 instead."},
{n:"Dimension Door",l:4,s:"Conjuration",ct:"Action",r:"500 ft.",c:"V",d:"Instant",k:0,x:"Teleport yourself and one willing creature to a known point in range."},
{n:"Divination",l:4,s:"Divination",ct:"Action (R)",r:"Self",c:"V,S,M",d:"Instant",k:0,x:"Truthful answer about an event within 7 days."},
{n:"Dominate Beast",l:4,s:"Enchantment",ct:"Action",r:"60 ft.",c:"V,S",d:"1 min",k:1,x:"Beast Wis save or Charmed and commanded; resave when damaged."},
{n:"Evard's Black Tentacles",l:4,s:"Conjuration",ct:"Action",r:"90 ft.",c:"V,S,M",d:"1 min",k:1,x:"20-ft square: Dex save or 3d6 bludgeoning and Restrained."},
{n:"Fabricate",l:4,s:"Transmutation",ct:"10 min",r:"120 ft.",c:"V,S",d:"Instant",k:0,x:"Convert raw materials into finished goods."},
{n:"Fire Shield",l:4,s:"Evocation",ct:"Action",r:"Self",c:"V,S,M",d:"10 min",k:0,x:"Warm/chill shield: resist cold/fire; melee attackers take 2d8."},
{n:"Fount of Moonlight",l:4,s:"Evocation",ct:"Action",r:"Self",c:"V,S",d:"10 min",k:1,x:"Light aura: resistance to radiant, +2d6 radiant on melee hits, blind reaction (2024)."},
{n:"Freedom of Movement",l:4,s:"Abjuration",ct:"Action",r:"Touch",c:"V,S,M",d:"1 hour",k:0,x:"Ignore difficult terrain; immune to Paralyzed/Restrained from magic; escape grapples."},
{n:"Giant Insect",l:4,s:"Conjuration",ct:"Action",r:"60 ft.",c:"V,S",d:"10 min",k:1,x:"Summon a Large insect spirit warrior (2024 version)."},
{n:"Grasping Vine",l:4,s:"Conjuration",ct:"Bonus Action",r:"60 ft.",c:"V,S",d:"1 min",k:1,x:"Vine attacks: 4d8 bludgeoning and pull 30 ft (2024). +1d8 per slot."},
{n:"Greater Invisibility",l:4,s:"Illusion",ct:"Action",r:"Touch",c:"V,S",d:"1 min",k:1,x:"Target Invisible even while attacking or casting."},
{n:"Guardian of Faith",l:4,s:"Conjuration",ct:"Action",r:"30 ft.",c:"V",d:"8 hours",k:0,x:"Spectral guardian: enemies within 10 ft, Dex save or 20 radiant; 60 dmg total."},
{n:"Hallucinatory Terrain",l:4,s:"Illusion",ct:"10 min",r:"300 ft.",c:"V,S,M",d:"24 hours",k:0,x:"150-ft cube of terrain looks like other terrain."},
{n:"Ice Storm",l:4,s:"Evocation",ct:"Action",r:"300 ft.",c:"V,S,M",d:"Instant",k:0,x:"20-ft cylinder: Dex save, 2d8 bludgeoning + 4d6 cold; difficult terrain. +1d8 per slot."},
{n:"Locate Creature",l:4,s:"Divination",ct:"Action",r:"Self",c:"V,S,M",d:"1 hour",k:1,x:"Sense direction to a familiar creature within 1,000 ft."},
{n:"Mordenkainen's Faithful Hound",l:4,s:"Conjuration",ct:"Action",r:"30 ft.",c:"V,S,M",d:"8 hours",k:0,x:"Invisible watchdog barks at intruders; bites 4d8 piercing."},
{n:"Mordenkainen's Private Sanctum",l:4,s:"Abjuration",ct:"10 min",r:"120 ft.",c:"V,S,M",d:"24 hours",k:0,x:"Ward an area vs sound, vision, scrying, teleport."},
{n:"Otiluke's Resilient Sphere",l:4,s:"Abjuration",ct:"Action",r:"30 ft.",c:"V,S,M",d:"1 min",k:1,x:"Dex save or sealed in an indestructible sphere."},
{n:"Phantasmal Killer",l:4,s:"Illusion",ct:"Action",r:"120 ft.",c:"V,S",d:"1 min",k:1,x:"Wis save or Frightened, 4d10 psychic each turn until save. +1d10 per slot."},
{n:"Polymorph",l:4,s:"Transmutation",ct:"Action",r:"60 ft.",c:"V,S,M",d:"1 hour",k:1,x:"Wis save or transformed into a Beast of CR ≤ its level/CR."},
{n:"Staggering Smite",l:4,s:"Enchantment",ct:"Bonus Action",r:"Self",c:"V",d:"1 min",k:0,x:"On weapon hit: +4d6 psychic, Wis save or Stunned until end of next turn (2024). +1d6 per slot."},
{n:"Stone Shape",l:4,s:"Transmutation",ct:"Action",r:"Touch",c:"V,S,M",d:"Instant",k:0,x:"Reshape a Medium stone object or 5-ft section."},
{n:"Stoneskin",l:4,s:"Transmutation",ct:"Action",r:"Touch",c:"V,S,M",d:"1 hour",k:1,x:"Resistance to nonmagical bludgeoning, piercing, slashing."},
{n:"Summon Aberration",l:4,s:"Conjuration",ct:"Action",r:"90 ft.",c:"V,S,M",d:"1 hour",k:1,x:"Aberrant spirit (Beholderkin/Slaad/Star Spawn) fights for you."},
{n:"Summon Construct",l:4,s:"Conjuration",ct:"Action",r:"90 ft.",c:"V,S,M",d:"1 hour",k:1,x:"Construct spirit (Clay/Metal/Stone) fights for you."},
{n:"Summon Elemental",l:4,s:"Conjuration",ct:"Action",r:"90 ft.",c:"V,S,M",d:"1 hour",k:1,x:"Elemental spirit (Air/Earth/Fire/Water) fights for you."},
{n:"Vitriolic Sphere",l:4,s:"Evocation",ct:"Action",r:"150 ft.",c:"V,S,M",d:"Instant",k:0,x:"20-ft sphere: Dex save, 10d4 acid + 5d4 next turn (2024). +2d4 per slot."},
{n:"Wall of Fire",l:4,s:"Evocation",ct:"Action",r:"120 ft.",c:"V,S,M",d:"1 min",k:1,x:"60-ft wall: 5d8 fire on creation and to those near one side. +1d8 per slot."},
{n:"Watery Sphere",l:4,s:"Conjuration",ct:"Action",r:"90 ft.",c:"V,S,M",d:"1 min",k:1,x:"10-ft sphere of water engulfs creatures (Str save or Restrained)."},

// ── Level 5 ────────────────────────────────────────────────────
{n:"Animate Objects",l:5,s:"Transmutation",ct:"Action",r:"120 ft.",c:"V,S",d:"1 min",k:1,x:"Objects attack: 1d12+mod force swarm (2024 version). More dice per slot."},
{n:"Antilife Shell",l:5,s:"Abjuration",ct:"Action",r:"Self (10-ft)",c:"V,S",d:"1 hour",k:1,x:"Barrier blocks living creatures from approaching within 10 ft."},
{n:"Awaken",l:5,s:"Transmutation",ct:"8 hours",r:"Touch",c:"V,S,M",d:"Instant",k:0,x:"Give a beast or plant Int 10, speech, and friendship (30 days)."},
{n:"Banishing Smite",l:5,s:"Conjuration",ct:"Bonus Action",r:"Self",c:"V",d:"1 min",k:1,x:"On weapon hit: +5d10 force; if ≤50 HP after, banished until spell ends."},
{n:"Bigby's Hand",l:5,s:"Evocation",ct:"Action",r:"120 ft.",c:"V,S,M",d:"1 min",k:1,x:"Large force hand: punch 5d8 (2024: 5d8+mod options), push, grasp, or block. +2d8 punch per slot."},
{n:"Circle of Power",l:5,s:"Abjuration",ct:"Action",r:"Self (30-ft)",c:"V",d:"10 min",k:1,x:"Aura: advantage on saves vs spells; half damage becomes none."},
{n:"Cloudkill",l:5,s:"Conjuration",ct:"Action",r:"120 ft.",c:"V,S",d:"10 min",k:1,x:"20-ft sphere of poison fog: Con save, 5d8 poison; moves away from you. +1d8 per slot."},
{n:"Commune",l:5,s:"Divination",ct:"1 min (R)",r:"Self",c:"V,S,M",d:"1 min",k:0,x:"Ask a deity three yes/no questions."},
{n:"Commune with Nature",l:5,s:"Divination",ct:"1 min (R)",r:"Self",c:"V,S",d:"Instant",k:0,x:"Learn three facts about terrain, water, creatures, structures within 3 miles."},
{n:"Cone of Cold",l:5,s:"Evocation",ct:"Action",r:"Self (60-ft cone)",c:"V,S,M",d:"Instant",k:0,x:"Con save, 8d8 cold (half on success). +1d8 per slot."},
{n:"Conjure Elemental",l:5,s:"Conjuration",ct:"Action",r:"60 ft.",c:"V,S",d:"10 min",k:1,x:"Elemental Restrains a creature: Dex save or Restrained, 8d8 damage/turn (2024). +2d8 per slot."},
{n:"Conjure Volley",l:5,s:"Conjuration",ct:"Action",r:"150 ft.",c:"V,S,M",d:"Instant",k:0,x:"40-ft cylinder: Dex save, 8d8 force (2024)."},
{n:"Contact Other Plane",l:5,s:"Divination",ct:"1 min (R)",r:"Self",c:"V",d:"1 min",k:0,x:"Ask an extraplanar entity five questions; Int save or take 6d6 psychic."},
{n:"Contagion",l:5,s:"Necromancy",ct:"Action",r:"Touch",c:"V,S",d:"7 days",k:0,x:"Melee spell attack; Con save or diseased (blinding, flesh rot, slimy doom...)."},
{n:"Creation",l:5,s:"Illusion",ct:"1 min",r:"30 ft.",c:"V,S,M",d:"Special",k:0,x:"Create a nonliving object of vegetable or mineral matter (5-ft cube)."},
{n:"Destructive Wave",l:5,s:"Evocation",ct:"Action",r:"Self (30-ft)",c:"V",d:"Instant",k:0,x:"Con save, 5d6 thunder + 5d6 radiant/necrotic and Prone."},
{n:"Dispel Evil and Good",l:5,s:"Abjuration",ct:"Action",r:"Self",c:"V,S,M",d:"1 min",k:1,x:"Celestials/elementals/fey/fiends/undead have disadvantage attacking you; break enchantment, dismiss."},
{n:"Dominate Person",l:5,s:"Enchantment",ct:"Action",r:"60 ft.",c:"V,S",d:"1 min",k:1,x:"Humanoid Wis save or Charmed and commanded; resave when damaged."},
{n:"Dream",l:5,s:"Illusion",ct:"1 min",r:"Special",c:"V,S,M",d:"8 hours",k:0,x:"Shape a sleeper's dreams; messenger or nightmare (3d6 psychic, no rest)."},
{n:"Flame Strike",l:5,s:"Evocation",ct:"Action",r:"60 ft.",c:"V,S,M",d:"Instant",k:0,x:"10-ft cylinder: Dex save, 5d6 fire + 5d6 radiant. +1d6 each per slot."},
{n:"Geas",l:5,s:"Enchantment",ct:"1 min",r:"60 ft.",c:"V",d:"30 days",k:0,x:"Wis save or magically commanded; 5d10 psychic for disobeying."},
{n:"Greater Restoration",l:5,s:"Abjuration",ct:"Action",r:"Touch",c:"V,S,M",d:"Instant",k:0,x:"End charm/petrification/curse, exhaustion level, or ability/HP max reduction."},
{n:"Hallow",l:5,s:"Abjuration",ct:"24 hours",r:"Touch",c:"V,S,M",d:"Until dispelled",k:0,x:"60-ft radius sacred: bars listed types, plus chosen extra effect."},
{n:"Hold Monster",l:5,s:"Enchantment",ct:"Action",r:"90 ft.",c:"V,S,M",d:"1 min",k:1,x:"Wis save or Paralyzed; resave each turn. +1 target per slot."},
{n:"Insect Plague",l:5,s:"Conjuration",ct:"Action",r:"300 ft.",c:"V,S,M",d:"10 min",k:1,x:"20-ft sphere of locusts: Con save, 4d10 piercing; difficult terrain. +1d10 per slot."},
{n:"Jallarzi's Storm of Radiance",l:5,s:"Evocation",ct:"Action",r:"120 ft.",c:"V,S,M",d:"1 min",k:1,x:"10-ft cylinder: Con save, 3d10 radiant + 3d10 thunder/turn; Blinded and Deafened inside (2024)."},
{n:"Legend Lore",l:5,s:"Divination",ct:"10 min",r:"Self",c:"V,S,M",d:"Instant",k:0,x:"Learn significant lore about a person, place, or object."},
{n:"Mass Cure Wounds",l:5,s:"Abjuration",ct:"Action",r:"60 ft.",c:"V,S",d:"Instant",k:0,x:"Up to 6 creatures in 30-ft sphere heal 5d8+mod (2024). +1d8 per slot."},
{n:"Mislead",l:5,s:"Illusion",ct:"Action",r:"Self",c:"S",d:"1 hour",k:1,x:"Become Invisible while an illusory double acts; see/hear through it."},
{n:"Modify Memory",l:5,s:"Enchantment",ct:"Action",r:"30 ft.",c:"V,S",d:"1 min",k:1,x:"Wis save or you reshape a memory from the last 24 hours."},
{n:"Passwall",l:5,s:"Transmutation",ct:"Action",r:"30 ft.",c:"V,S,M",d:"1 hour",k:0,x:"Passage through wood, plaster, or stone (5×8×20 ft)."},
{n:"Planar Binding",l:5,s:"Abjuration",ct:"1 hour",r:"60 ft.",c:"V,S,M",d:"24 hours",k:0,x:"Cha save or celestial/elemental/fey/fiend bound to your service."},
{n:"Raise Dead",l:5,s:"Necromancy",ct:"1 hour",r:"Touch",c:"V,S,M",d:"Instant",k:0,x:"Return a creature dead ≤10 days to life; −4 penalty fades over rests."},
{n:"Reincarnate",l:5,s:"Necromancy",ct:"1 hour",r:"Touch",c:"V,S,M",d:"Instant",k:0,x:"Dead humanoid reborn in a new random body."},
{n:"Scrying",l:5,s:"Divination",ct:"10 min",r:"Self",c:"V,S,M",d:"10 min",k:1,x:"Wis save or you see and hear a chosen creature remotely."},
{n:"Seeming",l:5,s:"Illusion",ct:"Action",r:"30 ft.",c:"V,S",d:"8 hours",k:0,x:"Disguise any number of creatures in range."},
{n:"Steel Wind Strike",l:5,s:"Conjuration",ct:"Action",r:"30 ft.",c:"S,M",d:"Instant",k:0,x:"Teleport-slash up to 5 creatures: melee spell attack, 6d10 force each."},
{n:"Summon Celestial",l:5,s:"Conjuration",ct:"Action",r:"90 ft.",c:"V,S,M",d:"1 hour",k:1,x:"Celestial spirit (Avenger/Defender) fights for you."},
{n:"Summon Dragon",l:5,s:"Conjuration",ct:"Action",r:"60 ft.",c:"V,S,M",d:"1 hour",k:1,x:"Draconic spirit fights for you (2024)."},
{n:"Swift Quiver",l:5,s:"Transmutation",ct:"Bonus Action",r:"Self",c:"V,S,M",d:"1 min",k:1,x:"Quiver makes ammo: two ranged weapon attacks as a bonus action each turn."},
{n:"Synaptic Static",l:5,s:"Enchantment",ct:"Action",r:"120 ft.",c:"V,S",d:"Instant",k:0,x:"20-ft sphere: Int save, 8d6 psychic and −1d6 on attacks/checks for 1 min."},
{n:"Telekinesis",l:5,s:"Transmutation",ct:"Action",r:"60 ft.",c:"V,S",d:"10 min",k:1,x:"Move 1,000 lb or contest to move a creature 30 ft each turn."},
{n:"Telepathic Bond",l:5,s:"Divination",ct:"Action (R)",r:"30 ft.",c:"V,S,M",d:"1 hour",k:0,x:"Eight willing creatures share telepathy any distance (same plane)."},
{n:"Teleportation Circle",l:5,s:"Conjuration",ct:"1 min",r:"10 ft.",c:"V,M",d:"1 round",k:0,x:"Portal to a known permanent circle anywhere on the plane."},
{n:"Tree Stride",l:5,s:"Conjuration",ct:"Action",r:"Self",c:"V,S",d:"1 min",k:1,x:"Step into a tree, out of another within 500 ft, once per turn."},
{n:"Wall of Force",l:5,s:"Evocation",ct:"Action",r:"120 ft.",c:"V,S,M",d:"10 min",k:1,x:"Invisible indestructible wall; immune to all damage, blocks ethereal."},
{n:"Wall of Stone",l:5,s:"Evocation",ct:"Action",r:"120 ft.",c:"V,S,M",d:"10 min",k:1,x:"Ten 10×10-ft stone panels; permanent if concentrated full duration."},
{n:"Yolande's Regal Presence",l:5,s:"Enchantment",ct:"Action",r:"Self (10-ft)",c:"V,S,M",d:"1 min",k:1,x:"Emanation: Wis save or 4d6 psychic, Prone, pushed 10 ft (2024)."},

// ── Level 6 ────────────────────────────────────────────────────
{n:"Arcane Gate",l:6,s:"Conjuration",ct:"Action",r:"500 ft.",c:"V,S",d:"10 min",k:1,x:"Linked teleportation portals at two points in range."},
{n:"Blade Barrier",l:6,s:"Evocation",ct:"Action",r:"90 ft.",c:"V,S",d:"10 min",k:1,x:"Wall of blades: Dex save, 6d10 slashing; three-quarters cover."},
{n:"Chain Lightning",l:6,s:"Evocation",ct:"Action",r:"150 ft.",c:"V,S,M",d:"Instant",k:0,x:"Bolt + 3 arcs: Dex save, 10d8 lightning each (half on success). +1 arc per slot."},
{n:"Circle of Death",l:6,s:"Necromancy",ct:"Action",r:"150 ft.",c:"V,S,M",d:"Instant",k:0,x:"60-ft sphere: Con save, 8d8 necrotic (2024: 8d8). +2d8 per slot."},
{n:"Conjure Fey",l:6,s:"Conjuration",ct:"Action",r:"60 ft.",c:"V,S",d:"10 min",k:1,x:"Fey spirit mirage: Wis save or 3d12 psychic and Frightened (2024). +2d12 per slot."},
{n:"Contingency",l:6,s:"Abjuration",ct:"10 min",r:"Self",c:"V,S,M",d:"10 days",k:0,x:"Stored spell (≤5th, Self) triggers on a described condition."},
{n:"Create Undead",l:6,s:"Necromancy",ct:"1 min",r:"10 ft.",c:"V,S,M",d:"Instant",k:0,x:"Raise up to three ghouls from corpses; control 24h. More/stronger per slot."},
{n:"Disintegrate",l:6,s:"Transmutation",ct:"Action",r:"60 ft.",c:"V,S,M",d:"Instant",k:0,x:"Dex save or 10d6+40 force; reduced to dust at 0 HP. +3d6 per slot."},
{n:"Drawmij's Instant Summons",l:6,s:"Conjuration",ct:"1 min (R)",r:"Touch",c:"V,S,M",d:"Until dispelled",k:0,x:"Sapphire recalls a prepared object to your hand."},
{n:"Eyebite",l:6,s:"Necromancy",ct:"Action",r:"Self",c:"V,S",d:"1 min",k:1,x:"Each turn: one creature Wis save or Asleep, Panicked, or Sickened."},
{n:"Find the Path",l:6,s:"Divination",ct:"1 min",r:"Self",c:"V,S,M",d:"1 day",k:1,x:"Know the shortest route to a fixed familiar destination."},
{n:"Flesh to Stone",l:6,s:"Transmutation",ct:"Action",r:"60 ft.",c:"V,S,M",d:"1 min",k:1,x:"Con save or Restrained, then Petrified after 3 failures."},
{n:"Forbiddance",l:6,s:"Abjuration",ct:"10 min (R)",r:"Touch",c:"V,S,M",d:"1 day",k:0,x:"40,000 sq ft warded vs teleport/planar travel; 5d10 to chosen types."},
{n:"Globe of Invulnerability",l:6,s:"Abjuration",ct:"Action",r:"Self (10-ft)",c:"V,S,M",d:"1 min",k:1,x:"Immobile barrier blocks spells of 5th level or lower."},
{n:"Guards and Wards",l:6,s:"Abjuration",ct:"10 min",r:"Touch",c:"V,S,M",d:"24 hours",k:0,x:"Fortify 2,500 sq ft: fog, locks, webs, and other defenses."},
{n:"Harm",l:6,s:"Necromancy",ct:"Action",r:"60 ft.",c:"V,S",d:"Instant",k:0,x:"Con save, 14d6 necrotic (half on success); reduces HP max."},
{n:"Heal",l:6,s:"Abjuration",ct:"Action",r:"60 ft.",c:"V,S",d:"Instant",k:0,x:"Heal 70 HP; ends Blinded, Deafened, diseases. +10 per slot."},
{n:"Heroes' Feast",l:6,s:"Conjuration",ct:"10 min",r:"30 ft.",c:"V,S,M",d:"Instant",k:0,x:"Feast: cure disease/poison, immune to Poisoned/Frightened, +2d10 max HP."},
{n:"Magic Jar",l:6,s:"Necromancy",ct:"1 min",r:"Self",c:"V,S,M",d:"Until dispelled",k:0,x:"Soul enters container; possess humanoids (Cha save)."},
{n:"Mass Suggestion",l:6,s:"Enchantment",ct:"Action",r:"60 ft.",c:"V,M",d:"24 hours",k:0,x:"Twelve creatures Wis save or follow a suggested course."},
{n:"Move Earth",l:6,s:"Transmutation",ct:"Action",r:"120 ft.",c:"V,S,M",d:"2 hours",k:1,x:"Reshape dirt/sand/clay in 40-ft squares over duration."},
{n:"Otiluke's Freezing Sphere",l:6,s:"Evocation",ct:"Action",r:"300 ft.",c:"V,S,M",d:"Instant",k:0,x:"60-ft sphere: Con save, 10d6 cold; freezes water. Throwable globe. +1d6 per slot."},
{n:"Otto's Irresistible Dance",l:6,s:"Enchantment",ct:"Action",r:"30 ft.",c:"V",d:"1 min",k:1,x:"Target dances: 0 speed, disadvantage on attacks/saves; Wis save to end (Charmed in 2024)."},
{n:"Planar Ally",l:6,s:"Conjuration",ct:"10 min",r:"60 ft.",c:"V,S",d:"Instant",k:0,x:"A deity sends a celestial/elemental/fiend; payment negotiable."},
{n:"Programmed Illusion",l:6,s:"Illusion",ct:"Action",r:"120 ft.",c:"V,S,M",d:"Until dispelled",k:0,x:"30-ft-cube illusion performs on a trigger."},
{n:"Summon Fiend",l:6,s:"Conjuration",ct:"Action",r:"90 ft.",c:"V,S,M",d:"1 hour",k:1,x:"Fiendish spirit (Demon/Devil/Yugoloth) fights for you."},
{n:"Sunbeam",l:6,s:"Evocation",ct:"Action",r:"Self (60-ft line)",c:"V,S,M",d:"1 min",k:1,x:"Beam each turn: Con save, 6d8 radiant and Blinded 1 turn."},
{n:"Tasha's Bubbling Cauldron",l:6,s:"Conjuration",ct:"Action",r:"5 ft.",c:"V,S,M",d:"10 min",k:0,x:"Cauldron of free common potions (2024)."},
{n:"Transport via Plants",l:6,s:"Conjuration",ct:"Action",r:"10 ft.",c:"V,S",d:"1 round",k:0,x:"Step into a Large plant, out of any other on the same plane."},
{n:"True Seeing",l:6,s:"Divination",ct:"Action",r:"Touch",c:"V,S,M",d:"1 hour",k:0,x:"Truesight 120 ft: see through illusions, invisibility, into Ethereal."},
{n:"Wall of Ice",l:6,s:"Evocation",ct:"Action",r:"120 ft.",c:"V,S,M",d:"10 min",k:1,x:"Ice wall: 10d6 cold passing through breaks; Dex save on creation. +2d6 per slot."},
{n:"Wall of Thorns",l:6,s:"Conjuration",ct:"Action",r:"120 ft.",c:"V,S,M",d:"10 min",k:1,x:"Brambles: Dex save, 7d8 piercing; slow costly passage. +1d8 per slot."},
{n:"Wind Walk",l:6,s:"Transmutation",ct:"1 min",r:"30 ft.",c:"V,S,M",d:"8 hours",k:0,x:"Eleven creatures become cloud-form, fly 300 ft."},
{n:"Word of Recall",l:6,s:"Conjuration",ct:"Action",r:"5 ft.",c:"V",d:"Instant",k:0,x:"Teleport you + 5 creatures to a prepared sanctuary."},

// ── Level 7 ────────────────────────────────────────────────────
{n:"Conjure Celestial",l:7,s:"Conjuration",ct:"Action",r:"90 ft.",c:"V,S",d:"10 min",k:1,x:"Radiant spirit pillar: heal or sear (4d12 radiant) where it moves (2024). +1d12 per slot."},
{n:"Delayed Blast Fireball",l:7,s:"Evocation",ct:"Action",r:"150 ft.",c:"V,S,M",d:"1 min",k:1,x:"Glowing bead: 12d6 fire, +1d6 per turn delayed; Dex save."},
{n:"Divine Word",l:7,s:"Evocation",ct:"Bonus Action",r:"30 ft.",c:"V",d:"Instant",k:0,x:"Cha save or effects by HP: deafened/blinded/stunned/killed; banishes extraplanar."},
{n:"Etherealness",l:7,s:"Conjuration",ct:"Action",r:"Self",c:"V,S",d:"8 hours",k:0,x:"Enter the Ethereal Plane's border. +3 willing creatures at slot 8+."},
{n:"Finger of Death",l:7,s:"Necromancy",ct:"Action",r:"60 ft.",c:"V,S",d:"Instant",k:0,x:"Con save, 7d8+30 necrotic; humanoids killed rise as your zombie."},
{n:"Fire Storm",l:7,s:"Evocation",ct:"Action",r:"150 ft.",c:"V,S",d:"Instant",k:0,x:"Ten 10-ft cubes: Dex save, 7d10 fire (half on success)."},
{n:"Forcecage",l:7,s:"Evocation",ct:"Action",r:"100 ft.",c:"V,S,M",d:"1 hour",k:1,x:"Invisible cage or box of force; Cha save to teleport out (2024: conc. up to 1 hr)."},
{n:"Mirage Arcane",l:7,s:"Illusion",ct:"10 min",r:"Sight",c:"V,S",d:"10 days",k:0,x:"1-mile-square terrain illusion, tactile and structural."},
{n:"Mordenkainen's Magnificent Mansion",l:7,s:"Conjuration",ct:"1 min",r:"300 ft.",c:"V,S,M",d:"24 hours",k:0,x:"Extradimensional mansion with food and servants."},
{n:"Mordenkainen's Sword",l:7,s:"Evocation",ct:"Action",r:"90 ft.",c:"V,S,M",d:"1 min",k:1,x:"Force blade: melee spell attack, 4d12+mod force (2024); move and strike as bonus action."},
{n:"Plane Shift",l:7,s:"Conjuration",ct:"Action",r:"Touch",c:"V,S,M",d:"Instant",k:0,x:"Eight willing creatures travel to another plane, or banish (Cha save)."},
{n:"Power Word Fortify",l:7,s:"Enchantment",ct:"Action",r:"60 ft.",c:"V",d:"Instant",k:0,x:"Distribute 120 temp HP among up to 6 creatures (2024)."},
{n:"Prismatic Spray",l:7,s:"Evocation",ct:"Action",r:"Self (60-ft cone)",c:"V,S",d:"Instant",k:0,x:"Random rays: 12d6 of various elements, restrain, petrify, or banish; Dex save."},
{n:"Project Image",l:7,s:"Illusion",ct:"Action",r:"500 miles",c:"V,S,M",d:"1 day",k:1,x:"Illusory double you see/hear through and puppet."},
{n:"Regenerate",l:7,s:"Transmutation",ct:"1 min",r:"Touch",c:"V,S,M",d:"1 hour",k:0,x:"Heal 4d8+15; 1 HP/min for an hour; regrow severed parts."},
{n:"Resurrection",l:7,s:"Necromancy",ct:"1 hour",r:"Touch",c:"V,S,M",d:"Instant",k:0,x:"Return a creature dead ≤100 years to life, full HP."},
{n:"Reverse Gravity",l:7,s:"Transmutation",ct:"Action",r:"100 ft.",c:"V,S,M",d:"1 min",k:1,x:"50-ft-radius cylinder: everything falls upward 100 ft."},
{n:"Sequester",l:7,s:"Transmutation",ct:"Action",r:"Touch",c:"V,S,M",d:"Until dispelled",k:0,x:"Hide a willing creature or object in stasis, invisible and undetectable."},
{n:"Simulacrum",l:7,s:"Illusion",ct:"12 hours",r:"Touch",c:"V,S,M",d:"Until dispelled",k:0,x:"Snow duplicate of a creature with half its HP, obeys you."},
{n:"Symbol",l:7,s:"Abjuration",ct:"1 min",r:"Touch",c:"V,S,M",d:"Until dispelled",k:0,x:"Inscribed glyph: Death (10d10), Fear, Sleep, Stun, and more."},
{n:"Teleport",l:7,s:"Conjuration",ct:"Action",r:"10 ft.",c:"V",d:"Instant",k:0,x:"You + 8 creatures to a destination by familiarity (mishap table)."},

// ── Level 8 ────────────────────────────────────────────────────
{n:"Animal Shapes",l:8,s:"Transmutation",ct:"Action",r:"30 ft.",c:"V,S",d:"24 hours",k:1,x:"Transform willing creatures into CR ≤4 beasts, re-shape at will."},
{n:"Antimagic Field",l:8,s:"Abjuration",ct:"Action",r:"Self (10-ft)",c:"V,S,M",d:"1 hour",k:1,x:"Sphere suppresses all magic inside: spells, items, summons."},
{n:"Antipathy/Sympathy",l:8,s:"Enchantment",ct:"1 hour",r:"60 ft.",c:"V,S,M",d:"10 days",k:0,x:"Object/area repels or attracts a creature kind (Wis save)."},
{n:"Befuddlement",l:8,s:"Enchantment",ct:"Action",r:"150 ft.",c:"V,S,M",d:"Instant",k:0,x:"Int save, 10d12 psychic, can't cast or take Magic action until Greater Restoration (2024, was Feeblemind)."},
{n:"Clone",l:8,s:"Necromancy",ct:"1 hour",r:"Touch",c:"V,S,M",d:"Instant",k:0,x:"Grow an inert duplicate body; soul transfers on death."},
{n:"Control Weather",l:8,s:"Transmutation",ct:"10 min",r:"Self (5 miles)",c:"V,S,M",d:"8 hours",k:1,x:"Shift precipitation, temperature, and wind by stages."},
{n:"Demiplane",l:8,s:"Conjuration",ct:"Action",r:"60 ft.",c:"S",d:"1 hour",k:0,x:"Door to a 30-ft-cube extradimensional room."},
{n:"Dominate Monster",l:8,s:"Enchantment",ct:"Action",r:"60 ft.",c:"V,S",d:"1 hour",k:1,x:"Wis save or Charmed and commanded; resave when damaged."},
{n:"Earthquake",l:8,s:"Transmutation",ct:"Action",r:"500 ft.",c:"V,S,M",d:"1 min",k:1,x:"100-ft-radius tremor: knock Prone, open fissures, topple structures."},
{n:"Glibness",l:8,s:"Enchantment",ct:"Action",r:"Self",c:"V",d:"1 hour",k:0,x:"Take 15 minimum on Charisma checks; lie detection sees truth."},
{n:"Holy Aura",l:8,s:"Abjuration",ct:"Action",r:"Self (30-ft)",c:"V,S,M",d:"1 min",k:1,x:"Allies: advantage on saves, attackers disadvantage; fiends/undead blinded on melee hit."},
{n:"Incendiary Cloud",l:8,s:"Conjuration",ct:"Action",r:"150 ft.",c:"V,S",d:"1 min",k:1,x:"20-ft sphere of embers: Dex save, 10d8 fire; moves away each turn."},
{n:"Maze",l:8,s:"Conjuration",ct:"Action",r:"60 ft.",c:"V,S",d:"10 min",k:1,x:"Banish to a labyrinth demiplane; DC 20 Int check to escape."},
{n:"Mind Blank",l:8,s:"Abjuration",ct:"Action",r:"Touch",c:"V,S",d:"24 hours",k:0,x:"Immune to psychic damage, mind reading, divination, charm."},
{n:"Power Word Stun",l:8,s:"Enchantment",ct:"Action",r:"60 ft.",c:"V",d:"Instant",k:0,x:"Stun a creature with 150 HP or fewer; Con save each turn to end."},
{n:"Sunburst",l:8,s:"Evocation",ct:"Action",r:"150 ft.",c:"V,S,M",d:"Instant",k:0,x:"60-ft-radius daylight: Con save, 12d6 radiant and Blinded 1 min."},
{n:"Telepathy",l:8,s:"Divination",ct:"Action",r:"Unlimited",c:"V,S,M",d:"24 hours",k:0,x:"Telepathic link with a familiar creature, any distance."},
{n:"Tsunami",l:8,s:"Conjuration",ct:"1 min",r:"Sight",c:"V,S",d:"6 rounds",k:1,x:"300×300-ft wave: Str save, 6d10 bludgeoning, sweeps creatures."},

// ── Level 9 ────────────────────────────────────────────────────
{n:"Astral Projection",l:9,s:"Necromancy",ct:"1 hour",r:"10 ft.",c:"V,S,M",d:"Special",k:0,x:"You + 8 project astral bodies onto the Astral Plane."},
{n:"Foresight",l:9,s:"Divination",ct:"1 min",r:"Touch",c:"V,S,M",d:"8 hours",k:0,x:"Target can't be surprised; advantage on everything; attackers disadvantage."},
{n:"Gate",l:9,s:"Conjuration",ct:"Action",r:"60 ft.",c:"V,S,M",d:"1 min",k:1,x:"Portal to another plane; can pull a named creature through."},
{n:"Imprisonment",l:9,s:"Abjuration",ct:"1 min",r:"30 ft.",c:"V,S,M",d:"Until dispelled",k:0,x:"Wis save or eternal prison: burial, chains, slumber, or minimus containment."},
{n:"Mass Heal",l:9,s:"Abjuration",ct:"Action",r:"60 ft.",c:"V,S",d:"Instant",k:0,x:"Distribute 700 HP of healing; cures blindness, deafness, disease."},
{n:"Meteor Swarm",l:9,s:"Evocation",ct:"Action",r:"1 mile",c:"V,S",d:"Instant",k:0,x:"Four 40-ft spheres: Dex save, 20d6 fire + 20d6 bludgeoning."},
{n:"Power Word Heal",l:9,s:"Enchantment",ct:"Action",r:"60 ft.",c:"V,S",d:"Instant",k:0,x:"Target heals all HP, ends charm/fright/paralysis/stun."},
{n:"Power Word Kill",l:9,s:"Enchantment",ct:"Action",r:"60 ft.",c:"V",d:"Instant",k:0,x:"A creature with 100 HP or fewer dies."},
{n:"Prismatic Wall",l:9,s:"Abjuration",ct:"Action",r:"60 ft.",c:"V,S",d:"10 min",k:0,x:"Seven-layered wall; each layer a different deadly effect."},
{n:"Shapechange",l:9,s:"Transmutation",ct:"Action",r:"Self",c:"V,S,M",d:"1 hour",k:1,x:"Become any creature CR ≤ level; keep mind, swap forms at will."},
{n:"Storm of Vengeance",l:9,s:"Conjuration",ct:"Action",r:"1 mile",c:"V,S",d:"1 min",k:1,x:"360-ft storm cloud: thunder, acid, lightning, hail, blinding fog by round."},
{n:"Time Stop",l:9,s:"Transmutation",ct:"Action",r:"Self",c:"V",d:"Instant",k:0,x:"Take 1d4+1 turns in a row; ends if you affect others."},
{n:"True Polymorph",l:9,s:"Transmutation",ct:"Action",r:"30 ft.",c:"V,S,M",d:"1 hour",k:1,x:"Transform creature↔creature/object; permanent if full duration."},
{n:"True Resurrection",l:9,s:"Necromancy",ct:"1 hour",r:"Touch",c:"V,S,M",d:"Instant",k:0,x:"Return a creature dead ≤200 years; no remains needed, full restore."},
{n:"Weird",l:9,s:"Illusion",ct:"Action",r:"120 ft.",c:"V,S",d:"1 min",k:1,x:"30-ft sphere: Wis save or Frightened, 10d10 psychic per turn (2024: 10d10 once + 5d10/turn)."},
{n:"Wish",l:9,s:"Conjuration",ct:"Action",r:"Self",c:"V",d:"Instant",k:0,x:"Duplicate any 8th-level spell, or reshape reality with risk."}
];

// ── Helpers ──────────────────────────────────────────────────────
var MM_SPELL_LEVELS = ['Cantrip','1st','2nd','3rd','4th','5th','6th','7th','8th','9th'];

function mmSpellByName(name) {
  var q = String(name||'').toLowerCase().trim();
  return MM_SPELLS.find(function(s){ return s.n.toLowerCase() === q; }) || null;
}
function mmSpellSearch(q, lvl) {
  q = String(q||'').toLowerCase().trim();
  return MM_SPELLS.filter(function(s){
    if (lvl !== undefined && lvl !== null && lvl !== '' && s.l !== Number(lvl)) return false;
    return !q || s.n.toLowerCase().indexOf(q) !== -1 || s.s.toLowerCase().indexOf(q) !== -1;
  });
}

// Ordinal label for a spell level (0 = Cantrip, 1 = "1st", …)
function mmSpellLevelLabel(l) { return MM_SPELL_LEVELS[l] || (l + 'th'); }

// Normalize a creature's spellcasting to the slots-based model:
//   { slots:{1..9:int}, list:[{ name, level, custom?, desc? }] }
// Cantrips (level 0) are cast at will; leveled spells draw on slots.
// Migrates the legacy { atwill:[], daily:[] } shape in place.
function mmNormSpells(m) {
  if (!m.spells) m.spells = {};
  var sp = m.spells;
  if (!Array.isArray(sp.list)) {
    var list = [];
    var slots = (sp.slots && typeof sp.slots === 'object') ? sp.slots : {};
    (sp.atwill || []).forEach(function(n){ var s = mmSpellByName(n); list.push({ name: s ? s.n : n, level: s ? s.l : 0 }); });
    (sp.daily || []).forEach(function(n){ var s = mmSpellByName(n); var lv = s ? s.l : 1; list.push({ name: s ? s.n : n, level: lv }); if (lv > 0) slots[lv] = Math.max(slots[lv] || 0, 1); });
    sp.list = list;
    sp.slots = slots;
    delete sp.atwill; delete sp.daily;
  }
  if (!sp.slots || typeof sp.slots !== 'object') sp.slots = {};
  return sp;
}
